version: "3.9"
services:
    postgres:
        env_file:
            - .env
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${GRUBBER_APP_DATABASE_USERNAME}"
            POSTGRES_PASSWORD: "${GRUBBER_APP_DATABASE_PASSWORD}"
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
volumes:
    postgres-data:
        driver: local
networks:
    default:
        external:
            name: "${DOCKER_NETWORK}"
